[package]
name = "solana_transaction_processor"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
crossbeam-channel = "0.5.3"
serde_json = "1.0.64"
env_logger = "0.9.0"
log = "0.4.11"
snafu = "0.7.2"

[profile.release]
opt-level = 3